name: khqr_sdk
description: "KHQR is a standardization of QR Code (EMV) that will promote wider use of mobile retail payments in Cambodia. By prescribing a KHQR (1 QR for all), a single KHQR Code can accept payments via different payment service operators (members of KHQR)."
maintainer: Mrr Hak
repository: https://github.com/mrrhak/khqr_sdk
issue_tracker: https://github.com/mrrhak/khqr_sdk/issues
homepage: https://mrrhak.com
version: 0.0.1-beta.1
funding:
  - https://ko-fi.com/mrrhak
screenshots:
  - description: "KHQR SDK"
    path: assets/khqr.png

topics:
  - khqr
  - khqr-sdk
  - bakong
  - bakong-khqr
  - khqr-code

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  plugin:
    platforms:
      android:
        package: com.mrrhak.khqr_sdk
        pluginClass: KhqrSdkPlugin
      ios:
        pluginClass: KhqrSdkPlugin
