name: khqr_sdk
description: 'Standardization of QR Code (EMV) that will promote wider use of mobile retail payments in Cambodia.'
maintainer: Mrr Hak
repository: https://github.com/mrrhak/khqr_sdk
issue_tracker: https://github.com/mrrhak/khqr_sdk/issues
homepage: https://mrrhak.com
version: 1.1.1
funding:
  - https://ko-fi.com/mrrhak
screenshots:
  - description: 'Bakong KHQR SDK'
    path: assets/khqr_sdk.png

topics:
  - khqr
  - khqr-sdk
  - khqr-code
  - bakong-khqr
  - bakong

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ">=0.18.1 <=0.20.2"
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  plugin_platform_interface: ^2.1.8
  pretty_qr_code: ^3.4.0
  flutter_svg: ^2.0.17
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.4

flutter:
  plugin:
    platforms:
      android:
        package: com.mrrhak.khqr_sdk
        pluginClass: KhqrSdkPlugin
      ios:
        pluginClass: KhqrSdkPlugin

  assets:
    - assets/fonts/nunito_sans/
    - assets/images/
    - assets/svg/

  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/nunito_sans/NunitoSans_7pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/nunito_sans/NunitoSans_7pt-Bold.ttf
          weight: 700
