name: Publish Package

on:
  release:
    types: [published]

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: '>> Dart package <<'
        uses: k-paxian/dart-package-publisher@v1.6
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          format: true
          force: false
          suppressBuildRunner: false
          dryRunOnly: false
          skipTests: false
